import React from 'react';

function Footer() {
  return (
    <>
      {/* Footer */}
      <div className="footer">
        {/* Support */}
        <div className="support-wrap extend-support">
          <div className="extend-wrap">
            <div className="extend-btn">
              <img src="/images/transparent.gif" title="customer" className="support-customer" alt="" />
              <a href="https://wa.link/skyexchcs" target="_blank" rel="noreferrer">Customer support1</a>
              <a href="https://wa.link/skyexchcs" target="_blank" rel="noreferrer" className="split-line">support2</a>
            </div>
            <div className="extend-btn">
              <img src="/images/transparent.gif" title="WhatsApp" className="support-whatsapp" alt="" />
              <a href="https://go.wa.link/skyexchange" target="_blank" rel="noreferrer">WhatsApp 3</a>
              <a href="https://go.wa.link/skyexchange" target="_blank" rel="noreferrer" className="split-line">WhatsApp 4</a>
            </div>
          </div>
          <div className="extend-btn mobile-btn"></div>
          <div className="extend-wrap mobile-wrap">
            <div className="support-social">
              <img src="/images/transparent.gif" title="Skype" className="support-skype" alt="" />
              <a href="skype:skyexchangeofficial?chat" target="_blank" rel="noreferrer">skyexchangeofficial</a>
            </div>
            <div className="support-social">
              <img src="/images/transparent.gif" title="Email" className="support-mail" alt="" />
              <a href="mailto:info@skyexchange.com" target="_blank" rel="noreferrer">info@skyexchange.com</a>
            </div>
            <div className="support-social">
              <img src="/images/transparent.gif" title="Instagram" className="support-ig" alt="" />
              <a href="https://www.instagram.com/skyexchoffficial/" target="_blank" rel="noreferrer">skyexchindia</a>
            </div>
          </div>
        </div>

        {/* Mobile Social Support */}
        <div className="support-social-mobile">
          <div className="support-social mobile-item">
            <img src="/images/transparent.gif" style={{ width: '20px', height: '20px' }} title="Skype" className="support-skype" alt="" />
            <a href="skype:skyexchangeofficial?chat" target="_blank" rel="noreferrer" style={{ color: '#00000080' }}>Skype</a>
          </div>
          <div className="support-social mobile-item">
            <img src="/images/transparent.gif" style={{ width: '20px', height: '20px' }} title="Email" className="support-mail" alt="" />
            <a href="mailto:info@skyexchange.com" target="_blank" rel="noreferrer" style={{ color: '#00000080' }}>Email</a>
          </div>
          <div className="support-social mobile-item1">
            <img src="/images/transparent.gif" style={{ width: '20px', height: '20px' }} title="Instagram" className="support-ig" alt="" />
            <a href="https://www.instagram.com/skyexchoffficial/" target="_blank" rel="noreferrer" style={{ color: '#00000080' }}>skyexchindia</a>
          </div>
        </div>
      </div>

      {/* Power Wrap */}
      <div className="power-wrap power-wrap_forsky">
        <h3 id="powerWrapW">
          <span>Powered by</span><img src="/images/transparent.gif" alt="" />
        </h3>
        <div className="licence_embed">
          <iframe
            src="https://licensing.gaming-curacao.com/validator/?lh=7a83475c9e54450a218a18bd28e33fad&template=seal"
            width="150"
            height="50"
            style={{ border: 'none' }}
            title="License"
          ></iframe>
        </div>
        <p>
          Skyexch.art is operated by Sky Infotech N.V. a limited liability
          company incorporated under the laws of Curacao with company
          Registration number 152377 with registered office at Abraham de
          Veerstraat 9, Curacao P.O Box 3421 and is licensed and regulated
          by the Curacao authority as the regulatory body responsible
          holding a (Sub-license with License number 365/JAZ Sub-License
          GLH- OCCHKTW0707072017 granted on 6.07.2017). <br />
          Players are requested not to contact any untrusted sources for{' '}
          <a href="https://www.skyexch.art" target="_blank" rel="noreferrer">https://www.skyexch.art/</a>{' '}
          accounts as this is an online site and they can only register
          independently without any agents. Only deposit through the account
          details generated by the system or provided by our official support team.
        </p>
        <div className="footer_info">
          <p className="icon_phone">
            <img src="/images/transparent.gif" alt="" />+351926917651 / +351926917279
          </p>
          <p>
            <a href="mailto:support@skyexch.art">
              <img src="/images/transparent.gif" alt="" />support@skyexch.art
            </a>
          </p>
        </div>
      </div>

      {/* Browser Support */}
      <div className="browser-wrap">
        <img src="/images/transparent.gif" alt="" /><br />
        Our website works best in the newest and last prior version of these browsers: <br />Google Chrome. Firefox
      </div>

      {/* Policy Links */}
      <ul className="policy-link">
        {[
          'Privacy Policy', 'Terms and Conditions', 'Rules and Regulations',
          'KYC', 'Responsible Gaming', 'About Us', 'Self-exclusion Policy', 'Underage Policy'
        ].map((item) => (
          <li key={item}>
            <a href="#" onClick={(e) => e.preventDefault()}>{item}</a>
          </li>
        ))}
      </ul>

      {/* App Download */}
      <div className="app-link" style={{ display: 'block' }}>
        <a href="#" onClick={(e) => e.preventDefault()}>
          <img src="/images/btn-appdl.png" alt="" />
        </a>
        <p>v1.15 - 2025-09-17 - 3.1MB</p>
      </div>
    </>
  );
}

export default Footer;
